// Generated by https://quicktype.io

export interface Movie {
    id:               number;
    title:            string;
    overview:         string;
    tagline:          string;
    budget:           number;
    revenue:          number;
    imdbUrl:          string;
    tmdbUrl:          null;
    posterUrl:        string;
    backdropUrl:      string;
    originalLanguage: null;
    releaseDate:      string;
    runTime:          number;
    price:            number;
    createdDate:      null;
    updatedDate:      null;
    updatedBy:        null;
    createdBy:        null;
    rating:           number;
    casts:            Cast[];
    genres:           Genre[];
}

export interface Cast {
    id:          number;
    name:        string;
    gender:      null;
    tmdbUrl:     null;
    profilePath: string;
    character:   string;
}

export interface Genre {
    id:   number;
    name: string;
}
